name: Build

on:
  push:
    branches: '*'
    tags: '*'
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x

    - name: Build with workaround
      run: |
        # Workaround for https://github.com/GitTools/GitVersion/issues/2838
        # if [[ $GITHUB_REF_TYPE == tag ]]; then
        #   echo Unsetting GITHUB_REF
        #   unset GITHUB_REF
        # fi
        dotnet build src

    - name: On Tag only
      id: release
      if: github.event_name == 'push' && github.ref_type == 'tag'
      run: |
        echo 'SemVer: ${{ env.GitVersion_SemVer }}'
