name: Build

on:
  push:
    branches: [ master ]
    tags: '*'
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Build
      run: |
        dotnet build src

    - name: Build with workaround
      run: |
        # Workaround for https://github.com/GitTools/GitVersion/issues/2838
        if [[ $GITHUB_REF_TYPE == tag ]]; then
          echo Unsetting GITHUB_REF
          unset GITHUB_REF
        fi
        dotnet build src

    - name: On Tag only
      id: release
      if: github.event_name == 'push' && github.ref_type == 'tag'
      run: |
        echo 'SemVer: ${{ env.GitVersion_SemVer }}'
